### PR TITLE
Update quiet-office.md

### PR DESCRIPTION
**Pull request by professor**

### CODE REVIEW

**Comment by kejadlen** [comment]
I'm also not sure about these studies, since empirically speaking, a lot of people like to work in coffeeshops and there's even [Coffitivity](https://coffitivity.com) for people who work better with a background hum of activity...

**Comment by benchristel** [comment]
@professor Thanks for the pull request! I'll add you as a member so you can commit future changes directly to `master` if you want.

Yes, I agree that "open plan offices don't work" is a huge overgeneralization. There is a range of office plans between bullpen and cubicle farm. IMO the sweet spot is somewhere in the middle, and it is probably a bit different for every individual.

Anecdotally, I've heard from many people that they do not like loud, crowded office environments (e.g. SF Labs circa 2016). While the background "hum" may work for some people, it also clearly isn't for everyone. Personally, I don't mind background noise, but then, I'm good at tuning things out.

We can break up the open/divided office plan continuum along several dimensions:

- Visual isolation from people on your own team doing similar work as yourself
- Visual isolation from people on other teams doing similar work as yourself
- Visual isolation from people on your own team doing a different type of work
- Visual isolation from people on other teams doing a different type of work
- Visual isolation from the outdoors
- Acoustic isolation from all of the above
- Number of people working in one team/group
- Size of the team's space relative to the number of people in it
- Ceiling height
- Acoustic properties of the space (is it echoey?)

and probably others.

What are the characteristics of the places where you most liked working, on all these dimensions? What are the characteristics of the places where you least liked working?

**Comment by benchristel** [comment]
I've merged the PR. We can continue the discussion here in the comments, or in the file itself (I slightly prefer using comments)

**Comment by benchristel** [comment]
@professor I found a paper on open-plan offices: https://espace.library.uq.edu.au/view/UQ:401844

Perhaps unsurprisingly, this researcher's answer to "do they work" is "it depends" 😛.

Disclaimer: I have not read the whole thing.

**Pull request merged**
